services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    environment:
      HOST: 0.0.0.0
      PORT: 4001
      DB_FILE_NAME: /app/data/database.sqlite
      SEED_DATABASE: "true"
    ports:
      - "4005:4001"
    volumes:
      - server_data:/app/data

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    environment:
      VITE_API_URL: http://localhost:4005
    ports:
      - "3005:3000"

volumes:
  server_data:
